# Generated by Django 4.0.2 on 2022-02-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_models',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
