# Generated by Django 4.0.2 on 2022-02-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_b_models_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_models',
            name='image',
            field=models.ImageField(blank=True, default='s1000rr.jpg', null=True, upload_to=''),
        ),
    ]
