# Generated by Django 4.0.2 on 2022-03-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
